name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch: # allows you to run manually from GitHub UI

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # REQUIRED to commit to the repository

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Pranavipulluri
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the generated snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
